### ISSUE TITLE
APU not avail for 45s after dual gen loss

### ISSUE THREAD

**Issue by merspieler** [Octal450/IDG-A32X#47]
### Expected Behavior
APU start is not available for 45 s after the loss of both engine generators. This 45 s delay prevents
any interference with emergency generator coupling.

### Current Behavior
APU can be started when ever you are happy to :D

See ELEC EMER CONFIG Procedure

**Comment by it0uchpods** [comment]
ON it's way

**Comment by legoboyvdlp** [comment]
We really need a better electric simulation and proper EMER ELEC. Once I get the 737 electric stable and working I'll port it to the A320 - it's just a matter of renaming the buses and implementing different logic

**Comment by it0uchpods** [comment]
I'll look into this shortly.

**Comment by Octal450** [comment]
Entire thing being rewritten
