### ISSUE TITLE
Tail Light (Which works) turns off when Flaps are retracted

### ISSUE THREAD

**Issue by andrewjoseofficial** [Octal450/IDG-A32X#95]
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
----
#### Expected Behavior (bug reports)
If you stay on the ground before take off and have flaps set to value greater than one, then tail lights work. But once you fly and climb, and set flaps to 0 and the tail appears black at night while other lights function

#### Requested Behavior  (feature requests)
Tail and logo lights work even after climbing and fully retracting flaps

#### Possible Solution (if applicable)
Check if accidentally code for the light is connected to the flaps. 
#### Steps to Reproduce (bug reports)

1. Set time to night
2. Turn on all external lights
3. Set flaps to 1
4. Take off and climb
5. Retract flaps fully
6. Light in tail is gone!
7. Extend flaps to 1 and light is back
8. Retract and the tail is black while other lights work.

**Comment by Octal450** [comment]
This is correct. Real Airbus does same. 

Kind Regards,
Josh

**Comment by andrewjoseofficial** [comment]
Is there a way to turn on them though in mid air?

**Comment by Octal450** [comment]
Sorry, no. As with the real plane (as far as I am aware, if you find out otherwise, link me and I'll correct it!)

Kind Regards,
Josh

**Comment by andrewjoseofficial** [comment]
I'll speak with some of my friends' parents who are actually pilots in Qatar Airways and ask them if there is such a thing, and how to enable it. Once I get an answer I will let you know.

**Comment by legoboyvdlp** [comment]
That will not be necessay because the manual is very clear on this:

![image](https://user-images.githubusercontent.com/10434911/59261917-2cd83400-8c36-11e9-8deb-397a5956e921.png)

**Comment by andrewjoseofficial** [comment]
Okay then. Can atleast the aesthetics of the tail be changed. Right now at night the tail is pitch black. It would be good if even though the lights are not there, the colors of the tail are mildly visible like the colors on the fuselage

**Comment by legoboyvdlp** [comment]
Once the new 3D is ready then that will be fixed ;)

**Comment by andrewjoseofficial** [comment]
Thank you for that. Nice plane by the way. I used to love the Boeing 777 on
FG, but now I love A32X very much. Soon I am keen on making FG movies
featuring the plane.

**Comment by Octal450** [comment]
I am very happy to hear you say.
Kind Regards,
Josh
