### ISSUE TITLE
FG Property Value missing?

### ISSUE THREAD

**Issue by fgfsUser4644** [Octal450/IDG-A32X#96]
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
----
FGFS does not accept the aircraft file (due to a missing file/property?). I have tried reinstalling the aircraft multiple times.

<img width="1277" alt="Screen Shot 2019-06-17 at 8 10 40 PM" src="https://user-images.githubusercontent.com/51934704/59644732-35e86a00-913c-11e9-8025-27af24c307b8.png">

**Comment by Octal450** [comment]
All sorted then?
I was going to say read INSTALL.md -- remove -master
