### ISSUE TITLE
Gears don't turn

### ISSUE THREAD

**Issue by 320stdg** [Octal450/IDG-A32X#97]
Goodmorning,

I have a bug sice many weeks: I can't turn the gears (left or right).
When I flight, it's not a problem, but on the ground, I must taxi with in push-back mode. It's not very realistic and it's slow.

I use this aircraft model since many months beacause it's very realistic, and I never had this problem before.
I have this problem just with the idg models, when i use the a320 of flightgear hangar, the gears works perfectly.
I tried to redownload many times the idg a32x model, and two times the flightgear simulator, but there is again this bug.
I have searched on internet, but I found nothing.

I don' know code very well, and it's what I don't touched the codes.
The problem is the aircraft model or flightgear simulator?

Have a nice day

**Comment by Octal450** [comment]
Hi sir,
Make sure you do not have auto-coordination on in your launcher. If you do, it will make the aileron axis control the tiller instead of the rudder axis.

Also, confirm that the pushback is turned off when you are trying to steer?

From my end steering appears to work.

Josh

**Comment by 320stdg** [comment]
Goodafternoon sir,

Thank you for your fast answer.
I've just tried without the auto-coordination and I confirm that the pushback is off, but it doesn't work: I can't turn.
For information, I have Windows 8.1 and Flightgear 2018.3.2.

Have a nice day

**Comment by Octal450** [comment]
Hello,
Please go to Debug -> Browse Internal Properties and tell me:

Go to controls/flight/rudder, does to move when you try to turn?

Also, does the exterior rudder move properly?

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
I can't remember if I animated the nose wheel steering switch in the cockpit, but make sure its on if it is, and there is no NWS STEER message or anything of the sort on the ECAM - may not be that exact message, but something about NWS steering (it comes up when pushback is enabled)

**Comment by 320stdg** [comment]
Hello,

I've gone to Browse International Properties, controls/flight/rudder,  and it move when I try.
The exterior rudder move too, but not the nose gear.
When the push back is enabled, the message who comes up is: (pushback): Pushback connected, please release brakes.

Have a nice day

**Comment by Octal450** [comment]
Hi sir, also know that the aircraft will not move the nose wheel if you are stopped. In real life, pilots must center the nose wheel when stopping.

Other than that, I literally have no clue.

**Comment by 320stdg** [comment]
Hello sir,

It doesn't work! I don't know why.
Thank you for your help.

Have a nice day

**Comment by Octal450** [comment]
That is really strange!

The only other thing I can wonder is ifbyou have any console messages. Could you start FG, see that it don't work, then close FG and send me fgfs.log? (It is in $FG_HOME, which is %appdata%\flightgear.org on Windows)

Kind Regards,
Josh

**Comment by 320stdg** [comment]
Goodafternoon sir,

Today, when I've launched Flightgear, I saw a message who sayed that there was a new version. I've downloaded it and know everything works! I'm so happy!
Thank you for your help, and I want to say that I like this model of a320, it's very realistic.
Thank you for everything

Have a nice day

**Comment by Octal450** [comment]
That's fantastic to here! Enjoy!

Kind Regards,
Josh
