### ISSUE TITLE
ECAM metric system

### ISSUE THREAD

**Issue by vezza** [Octal450/IDG-A32X#98]
### General
----

I am submitting a: (select one) 
* [ ] Bug report
* [x] Feature request

### Details
----
#### Requested Behavior  (feature requests)

As the A320 is built by an European company (Airbus) the default ECAM system units should be visualized with metric system (example: Fuel Flow should be KG/H instead LBS/H). To be honest I don't know if the operator or the pilots can change the unit system between metric and imperial...

#### Steps to Reproduce (bug reports)

![A320_ECAM](https://user-images.githubusercontent.com/1450066/63668028-23db1580-c7d6-11e9-89a2-be3c1c4181fa.png)

**Comment by legoboyvdlp** [comment]
Hi:
First - that is the CRT version, not the LCD version.
Second - there is a "pin" (more like a circuit breaker) in the avionics bay to switch between LBS and KG.  LBS certainly are an option.

**Comment by vezza** [comment]
Ok thanks

**Comment by Octal450** [comment]
During the rework of the displays, this will be addressed!

Already on the list so this is duplicate

Kind Regards,
Josh
