### ISSUE TITLE
Sound problem from outside views

### ISSUE THREAD

**Issue by yanfiz** [Octal450/IDG-A32X#99]
### General
----

I am submitting a:
* [x] Bug report
* [ ] Feature request

### Details
I can't hear engine sounds from outside views of the A320-271N and A320-251N models. A320-232, A320-111 and A320-214 models are OK.
#### Expected Behavior (bug reports)

I expected to hear the sounds of running engines.
#### Current Behavior (if applicable)

During starting engines manually or automatically, I can hear engine sounds. As soon as engines are started, sounds are fading out, --sounds like that engines are going to stop-- and finally they are being silence.

#### Steps to Reproduce (bug reports)

1.  Run FlightGear.
2.  Select Airbus A320-271N or A320-251N
3.  Start engines.
4.  Just listen the sounds from outside of aircraft.

### Additional information

To make a fresh test, I am deleting all files and folders expect FlightGear, autosave_2019_1.xml, navdata_2019_1.cache in \AppData\Roaming\flightgear.org. I'm doing this, because I'm able to bypass RAT deploying issue that also mentioned in 80 numbered "A32X spawns with RAT deployed" issue.

**Comment by Octal450** [comment]
👌 👍 
Looking into it.

Kind Regards,
Josh
